config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  get "/stats" => "stats#index"

  resources :trainings
  resources :users

end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :user
  validates :name, length: { minimum: 3 }
  validates :date, presence: true
  validates :weight, numericality: { only_integer: true }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :trainings, dependent: :destroy

	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates :email, :password, presence: true
	validates :email, uniqueness: true
	
	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

	def self.authenticate(email, password)
		user = User.where(email: email).first
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end



	helper_method :current_user
	protect_from_forgery with: :exception

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
  	end
  	
  	def create
		@user = User.authenticate(params[:email], params[:password])
		if @user
			#flash[:notice] = "You've been logged in."
			session[:user_id] = @user.id
			redirect_to "/trainings/"
		else
			flash[:alert] = "There was a problem logging you in."
			redirect_to log_in_path
		end
	end
  	
  	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've been logged out successfully."
		redirect_to "/"
	end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
	def index
		unless current_user.nil?
      		@trainings = Training.where(:user_id => current_user.id).order('date DESC')
      		render json: @trainings
    	else
      		redirect_to '/log-in/'
    	end
	end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
	def index
    unless current_user.nil?
      #@trainings = Training.where(:user_id => current_user.id)
      #@uniq_trainings = Training.where(:user_id => current_user.id).group("name")
      @trainings = Training.where(:user_id => current_user.id).order('date DESC')
    else
      redirect_to '/log-in/'
    end
	end

	def show
    	@training = Training.find(params[:id])
	end

	def new
    unless current_user.nil?
      @training = Training.new
      @user_id = current_user.id
    else
      redirect_to '/log-in/'
    end
	end

	def edit
  		#@training = Training.find(params[:id])
      render nothing: true
	end

	def create
      training_params.inspect
  		@training = Training.new(training_params)
  		if @training.save
  			redirect_to '/trainings/'
  		else
  			render 'new'
  		end
	end

	def update
  		@training = Training.find(params[:id])
  		if @training.update(training_params)
    		redirect_to @training
  		else
    		render 'edit'
  		end
  end
 
  def destroy
    @training = Training.find(params[:id])
    @training.destroy
    redirect_to 'trainings'
  end

	private

  		def training_params
    		params.require(:training).permit(:name, :date, :weight, :user_id)
  		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to 'new_training_path'
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      #redirect_to :back
      render 'users/new'
    end
  end

  def update
  end

  def destroy
  end

  def new
    @user = User.new
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	unless current_user.nil?
  		redirect_to '/trainings/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deargravity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/index.html.erb
<%= @trainings.to_json %>

app/views/trainings/_form.html.erb
<%= form_for @training do |f| %>

	<% if @training.errors.any? %>
    	<div id="error_explanation">
      		<h2>
        		<%= pluralize(@training.errors.count, "error") %> prohibited
        		this training from being saved:
      		</h2>
      		<ul>
        		<% @training.errors.full_messages.each do |msg| %>
          		<li><%= msg %></li>
        		<% end %>
      		</ul>
    	</div>
  	<% end %>

  <div class="form-group">
    <%= f.label :date, :value => "Дата" ,:class => "control-label" %><br>
    <%= f.date_field :date, :class => "form-control" %>
  </div>
 

   <div class="form-group">
    <%= f.label :name, :value => "Название", :class => "control-label" %><br>
    <%= f.text_field :name, :class => "form-control uniq_trainnings", :placeholder => "Штанга :: Становая" %>
  </div>
 

  <div class="form-group">
    <%= f.label :weight, :value => "Достижение (кг/км/раз)", :class => "control-label" %><br>
    <%= f.text_field :weight, :class => "form-control", :placeholder => "40" %>
  </div>

  <div class="form-group">
    <%= f.hidden_field :user_id, :value => @user_id %>
  </div>

  <div class="form-group">
    <%= f.submit nil, :class => "btn btn-primary btn-lg btn-block", :value => "Сохранить" %>
  </div>

<% end %>

app/views/trainings/edit.html.erb
<h3>Редактировать упражнение</h3>
 
<%= render 'form' %>
 
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<!-- <h3>Упражнения</h3> -->

<%= link_to 'Записать результат', new_training_path, :class => "btn btn-primary btn-lg btn-block" %>

<br />

<% trainings_by_date = @trainings.group_by(&:date) %>

<% trainings_by_date.each do |t| %>
  <h4><%= Russian::strftime(t[0], "%e %b, %Y").split(',').join(',<small>').html_safe %></small></h4>
  <div class="list-group">
  <% t[1].each do |z| %> 
    <a class="list-group-item"><%= z.name %> <span class="pull-right"><%= z.weight %></span></a>
  <% end %>
  </div>
<%end %>

<br />
<%= link_to 'Выйти', '/log-out/', :class => "btn btn-default btn-lg btn-block" %>

app/views/trainings/new.html.erb
<h3>Новый результат</h3>

<%= render 'form' %>
<%= link_to 'Отменить', trainings_path, :class => "btn btn-default btn-lg btn-block" %>

app/views/trainings/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @training.date %>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @training.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @training.weight %>
</p>
 
<%= link_to 'Edit', edit_training_path(@training) %> | <%= link_to 'Назад', trainings_path %>

app/views/users/new.html.erb
<h3>Регистрация</h3>
<%=form_for User.new do |f| %>
	<% if @user.errors.any? %>
	<% end %>
    
    <% @user.errors.full_messages.each do |msg| %>
    	<p><%= msg %></p>
    <% end %>

	<div class="form-group">
		<%=f.label :email, :class => "control-label" %>
		<%=f.text_field :email, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%=f.label :password, :class => "control-label" %>
		<%=f.password_field :password, :class => "form-control" %>
	</div>

	<div class="form-group">
		<%=f.label :password_confirmation, :class => "control-label" %>
		<%=f.password_field :password_confirmation, :class => "form-control" %>
	</div>
	
	<div class="form-group">
		<%=f.submit nil, :class => "btn btn-primary btn-lg btn-block", :value => "Зарегистрироваться" %>
	</div>

<%end%>

app/views/welcome/index.html.erb
<h3>DearGravity</h3>
<p>Простой блокнот для хранения спортивных достижений.</p>
<br />
<div class="well">
	<%= link_to 'Войти', 'log-in/', :class => "btn btn-primary btn-lg btn-block" %>
	<%= link_to 'Зарегистрироваться', 'users/new/', :class => "btn btn-primary btn-lg btn-block" %>
</div>